export default [
    {
        nombre: "Esmeralda del génesis",
        rareza: 5,
        tipo: "espada",
        tipoImg: require("@/assets/images/tipos-armas/weapon_espada.webp"),
        armaImg: require("@/assets/images/armas/esmeraldadelgenesis.webp"),
    },
    {
        nombre: "Ondas cósmicas",
        rareza: 5,
        tipo: "rectificador",
        tipoImg: require("@/assets/images/tipos-armas/weapon_rectificador.webp"),
        armaImg: require("@/assets/images/armas/ondascosmicas.webp"),
    },
    {
        nombre: "Niebla estática",
        rareza: 5,
        tipo: "pistolas",
        tipoImg: require("@/assets/images/tipos-armas/weapon_pistolas.webp"),
        armaImg: require("@/assets/images/armas/nieblaestatica.webp"),
    },
    {
        nombre: "Navaja brillante",
        rareza: 5,
        tipo: "mandoble",
        tipoImg: require("@/assets/images/tipos-armas/weapon_mandoble.webp"),
        armaImg: require("@/assets/images/armas/navajabrillante.webp"),
    },
    {
        nombre: "Oleadas del abismo",
        rareza: 5,
        tipo: "brazales",
        tipoImg: require("@/assets/images/tipos-armas/weapon_brazales.webp"),
        armaImg: require("@/assets/images/armas/oleadasdelabismo.webp"),
    },
    {
        nombre: "Cumbre verde",
        rareza: 5,
        tipo: "mandoble",
        tipoImg: require("@/assets/images/tipos-armas/weapon_mandoble.webp"),
        armaImg: require("@/assets/images/armas/verdantsummit.webp"),
    },
    {
        nombre: "Maestro de cuerdas",
        rareza: 5,
        tipo: "rectificador",
        tipoImg: require("@/assets/images/tipos-armas/weapon_rectificador.webp"),
        armaImg: require("@/assets/images/armas/stringmaster.webp"),
    },
    {
        nombre: "Eras de cosecha",
        rareza: 5,
        tipo: "mandoble",
        tipoImg: require("@/assets/images/tipos-armas/weapon_mandoble.webp"),
        armaImg: require("@/assets/images/armas/agesofharvest.webp"),
    },
    {
        nombre: "Brillo abrasador",
        rareza: 5,
        tipo: "espada",
        tipoImg: require("@/assets/images/tipos-armas/weapon_espada.webp"),
        armaImg: require("@/assets/images/armas/blazingbrilliance.webp"),
    },
    {
        nombre: "Espina de la desafiadora",
        rareza: 5,
        tipo: "espada",
        tipoImg: require("@/assets/images/tipos-armas/weapon_espada.webp"),
        armaImg: require("@/assets/images/armas/defiersthorn.webp"),
    },
    {
        nombre: "Brotes escarchados",
        rareza: 5,
        tipo: "rectificador",
        tipoImg: require("@/assets/images/tipos-armas/weapon_rectificador.webp"),
        armaImg: require("@/assets/images/armas/rimedraped.webp"),
    },
    {
        nombre: "Mango de la verdad",
        rareza: 5,
        tipo: "brazales",
        tipoImg: require("@/assets/images/tipos-armas/weapon_brazales.webp"),
        armaImg: require("@/assets/images/armas/verity.webp"),
    },
    {
        nombre: "Sinfonía estelar",
        rareza: 5,
        tipo: "rectificador",
        tipoImg: require("@/assets/images/tipos-armas/weapon_rectificador.webp"),
        armaImg: require("@/assets/images/armas/stellarsymphony.webp"),
    },
    {
        nombre: "Primavera roja",
        rareza: 5,
        tipo: "espada",
        tipoImg: require("@/assets/images/tipos-armas/weapon_espada.webp"),
        armaImg: require("@/assets/images/armas/redspring.webp"),
    },
    {
        nombre: "Tragicomedia",
        rareza: 5,
        tipo: "brazales",
        tipoImg: require("@/assets/images/tipos-armas/weapon_brazales.webp"),
        armaImg: require("@/assets/images/armas/tragicomedy.webp"),
    },
    {
        nombre: "Último baile",
        rareza: 5,
        tipo: "pistolas",
        tipoImg: require("@/assets/images/tipos-armas/weapon_pistolas.webp"),
        armaImg: require("@/assets/images/armas/lastdance.webp"),
    },
    {
        nombre: "Valor inquebrantable",
        rareza: 5,
        tipo: "espada",
        tipoImg: require("@/assets/images/tipos-armas/weapon_espada.webp"),
        armaImg: require("@/assets/images/armas/unflickering.webp"),
    },
    {
        nombre: "Himno luminoso",
        rareza: 5,
        tipo: "rectificador",
        tipoImg: require("@/assets/images/tipos-armas/weapon_rectificador.webp"),
        armaImg: require("@/assets/images/armas/luminoushymn.webp"),
    },
    {
        nombre: "Susurros de sirenas",
        rareza: 5,
        tipo: "rectificador",
        tipoImg: require("@/assets/images/tipos-armas/weapon_rectificador.webp"),
        armaImg: require("@/assets/images/armas/whispersofsirens.webp"),
    },
    {
        nombre: "Pacto de sangre",
        rareza: 5,
        tipo: "espada",
        tipoImg: require("@/assets/images/tipos-armas/weapon_espada.webp"),
        armaImg: require("@/assets/images/armas/bloodpacts.webp"),
    },
    {
        nombre: "Veredicto del destello",
        rareza: 5,
        tipo: "brazales",
        tipoImg: require("@/assets/images/tipos-armas/weapon_brazales.webp"),
        armaImg: require("@/assets/images/armas/blazingjustice.webp"),
    },
    {
        nombre: "Aria del bosque",
        rareza: 5,
        tipo: "pistolas",
        tipoImg: require("@/assets/images/tipos-armas/weapon_pistolas.webp"),
        armaImg: require("@/assets/images/armas/woodlandaria.webp"),
    },
    {
        nombre: "Disonancia",
        rareza: 4,
        tipo: "mandoble",
        tipoImg: require("@/assets/images/tipos-armas/weapon_mandoble.webp"),
        armaImg: require("@/assets/images/armas/discord.webp"),
    },
    {
        nombre: "Obertura",
        rareza: 4,
        tipo: "espada",
        tipoImg: require("@/assets/images/tipos-armas/weapon_espada.webp"),
        armaImg: require("@/assets/images/armas/overture.webp"),
    },
    {
        nombre: "Cadenza",
        rareza: 4,
        tipo: "pistolas",
        tipoImg: require("@/assets/images/tipos-armas/weapon_pistolas.webp"),
        armaImg: require("@/assets/images/armas/cadenza.webp"),
    },
    {
        nombre: "Marcato",
        rareza: 4,
        tipo: "brazales",
        tipoImg: require("@/assets/images/tipos-armas/weapon_brazales.webp"),
        armaImg: require("@/assets/images/armas/marcato.webp"),
    },
    {
        nombre: "Variación",
        rareza: 4,
        tipo: "rectificador",
        tipoImg: require("@/assets/images/tipos-armas/weapon_rectificador.webp"),
        armaImg: require("@/assets/images/armas/variation.webp"),
    },
    {
        nombre: "Mandoble #41",
        rareza: 4,
        tipo: "mandoble",
        tipoImg: require("@/assets/images/tipos-armas/weapon_mandoble.webp"),
        armaImg: require("@/assets/images/armas/broadblade41.webp"),
    },
    {
        nombre: "Espada #18",
        rareza: 4,
        tipo: "espada",
        tipoImg: require("@/assets/images/tipos-armas/weapon_espada.webp"),
        armaImg: require("@/assets/images/armas/sword18.webp"),
    },
    {
        nombre: "Rectificador #25",
        rareza: 4,
        tipo: "rectificador",
        tipoImg: require("@/assets/images/tipos-armas/weapon_rectificador.webp"),
        armaImg: require("@/assets/images/armas/rectifier25.webp"),
    },
    {
        nombre: "Noche intrépida",
        rareza: 4,
        tipo: "mandoble",
        tipoImg: require("@/assets/images/tipos-armas/weapon_mandoble.webp"),
        armaImg: require("@/assets/images/armas/dauntlessevernight.webp"),
    },
    {
        nombre: "Comando de convicción",
        rareza: 4,
        tipo: "espada",
        tipoImg: require("@/assets/images/tipos-armas/weapon_espada.webp"),
        armaImg: require("@/assets/images/armas/commandoofconviction.webp"),
    },
    {
        nombre: "Llama eterna",
        rareza: 4,
        tipo: "pistolas",
        tipoImg: require("@/assets/images/tipos-armas/weapon_pistolas.webp"),
        armaImg: require("@/assets/images/armas/undyingflame.webp"),
    },
    {
        nombre: "Acuerdo de amistad",
        rareza: 4,
        tipo: "brazales",
        tipoImg: require("@/assets/images/tipos-armas/weapon_brazales.webp"),
        armaImg: require("@/assets/images/armas/amityaccord.webp"),
    },
    {
        nombre: "Guardián de Jinzhou",
        rareza: 4,
        tipo: "rectificador",
        tipoImg: require("@/assets/images/tipos-armas/weapon_rectificador.webp"),
        armaImg: require("@/assets/images/armas/jinzhoukeeper.webp"),
    },
    {
        nombre: "Espada de Helios",
        rareza: 4,
        tipo: "mandoble",
        tipoImg: require("@/assets/images/tipos-armas/weapon_mandoble.webp"),
        armaImg: require("@/assets/images/armas/helioscleaver.webp"),
    },
    {
        nombre: "Cortador lunar",
        rareza: 4,
        tipo: "espada",
        tipoImg: require("@/assets/images/tipos-armas/weapon_espada.webp"),
        armaImg: require("@/assets/images/armas/lunarcutter.webp"),
    },
    {
        nombre: "Novaestallido",
        rareza: 4,
        tipo: "pistolas",
        tipoImg: require("@/assets/images/tipos-armas/weapon_pistolas.webp"),
        armaImg: require("@/assets/images/armas/novaburst.webp"),
    },
    {
        nombre: "Llamarada de cometa",
        rareza: 4,
        tipo: "rectificador",
        tipoImg: require("@/assets/images/tipos-armas/weapon_rectificador.webp"),
        armaImg: require("@/assets/images/armas/cometflare.webp"),
    },
    {
        nombre: "Pistolas #26",
        rareza: 4,
        tipo: "pistolas",
        tipoImg: require("@/assets/images/tipos-armas/weapon_pistolas.webp"),
        armaImg: require("@/assets/images/armas/pistols26.webp"),
    },
    {
        nombre: "Brazales #21D",
        rareza: 4,
        tipo: "brazales",
        tipoImg: require("@/assets/images/tipos-armas/weapon_brazales.webp"),
        armaImg: require("@/assets/images/armas/gauntlets21d.webp"),
    },
    {
        nombre: "Rastro de otoño",
        rareza: 4,
        tipo: "mandoble",
        tipoImg: require("@/assets/images/tipos-armas/weapon_mandoble.webp"),
        armaImg: require("@/assets/images/armas/autumntrace.webp"),
    },
    {
        nombre: "Lumingloss",
        rareza: 4,
        tipo: "espada",
        tipoImg: require("@/assets/images/tipos-armas/weapon_espada.webp"),
        armaImg: require("@/assets/images/armas/lumingloss.webp"),
    },
    {
        nombre: "Rayo",
        rareza: 4,
        tipo: "pistolas",
        tipoImg: require("@/assets/images/tipos-armas/weapon_pistolas.webp"),
        armaImg: require("@/assets/images/armas/thunderbolt.webp"),
    },
    {
        nombre: "Stonard",
        rareza: 4,
        tipo: "brazales",
        tipoImg: require("@/assets/images/tipos-armas/weapon_brazales.webp"),
        armaImg: require("@/assets/images/armas/stonard.webp"),
    },
    {
        nombre: "Consonante sorda",
        rareza: 4,
        tipo: "rectificador",
        tipoImg: require("@/assets/images/tipos-armas/weapon_rectificador.webp"),
        armaImg: require("@/assets/images/armas/augment.webp"),
    },
    {
        nombre: "Corrimiento al rojo",
        rareza: 4,
        tipo: "mandoble",
        tipoImg: require("@/assets/images/tipos-armas/weapon_mandoble.webp"),
        armaImg: require("@/assets/images/armas/waningredshift.webp"),
    },
    {
        nombre: "Colapso interminable",
        rareza: 4,
        tipo: "espada",
        tipoImg: require("@/assets/images/tipos-armas/weapon_espada.webp"),
        armaImg: require("@/assets/images/armas/endlesscollapse.webp"),
    },
    {
        nombre: "Chorro relativista",
        rareza: 4,
        tipo: "pistolas",
        tipoImg: require("@/assets/images/tipos-armas/weapon_pistolas.webp"),
        armaImg: require("@/assets/images/armas/relativisticjet.webp"),
    },
    {
        nombre: "Acreción de fusión",
        rareza: 4,
        tipo: "rectificador",
        tipoImg: require("@/assets/images/tipos-armas/weapon_rectificador.webp"),
        armaImg: require("@/assets/images/armas/fusionaccretion.webp"),
    },
    {
        nombre: "Espejismo hueco",
        rareza: 4,
        tipo: "brazales",
        tipoImg: require("@/assets/images/tipos-armas/weapon_brazales.webp"),
        armaImg: require("@/assets/images/armas/hollowmirage.webp"),
    },
    {
        nombre: "Espiral celestial",
        rareza: 4,
        tipo: "brazales",
        tipoImg: require("@/assets/images/tipos-armas/weapon_brazales.webp"),
        armaImg: require("@/assets/images/armas/celestialspiral.webp"),
    },
    {
        nombre: "Ancla de Somnolencia",
        rareza: 4,
        tipo: "espada",
        tipoImg: require("@/assets/images/tipos-armas/weapon_espada.webp"),
        armaImg: require("@/assets/images/armas/somnoireanchor.webp"),
    },
    {
        nombre: "Llamada del abismo",
        rareza: 4,
        tipo: "rectificador",
        tipoImg: require("@/assets/images/tipos-armas/weapon_rectificador.webp"),
        armaImg: require("@/assets/images/armas/calloftheabyss.webp"),
    },
    {
        nombre: "Meditaciones de la piedad",
        rareza: 4,
        tipo: "mandoble",
        tipoImg: require("@/assets/images/tipos-armas/weapon_mandoble.webp"),
        armaImg: require("@/assets/images/armas/meditationsonmercy.webp"),
    },
    {
        nombre: "Fábulas de sabiduría",
        rareza: 4,
        tipo: "espada",
        tipoImg: require("@/assets/images/tipos-armas/weapon_espada.webp"),
        armaImg: require("@/assets/images/armas/fablesofwisdom.webp"),
    },
    {
        nombre: "Romance de la despedida",
        rareza: 4,
        tipo: "pistolas",
        tipoImg: require("@/assets/images/tipos-armas/weapon_pistolas.webp"),
        armaImg: require("@/assets/images/armas/romanceinfarewell.webp"),
    },
    {
        nombre: "Crónica del héroe ebrio",
        rareza: 4,
        tipo: "brazales",
        tipoImg: require("@/assets/images/tipos-armas/weapon_brazales.webp"),
        armaImg: require("@/assets/images/armas/legendofdrunkenhero.webp"),
    },
    {
        nombre: "Vals enmascarado",
        rareza: 4,
        tipo: "rectificador",
        tipoImg: require("@/assets/images/tipos-armas/weapon_rectificador.webp"),
        armaImg: require("@/assets/images/armas/waltzinmasquerade.webp"),
    },
    {
        nombre: "Mandoble de la noche",
        rareza: 3,
        tipo: "mandoble",
        tipoImg: require("@/assets/images/tipos-armas/weapon_mandoble.webp"),
        armaImg: require("@/assets/images/armas/broadbladeofnight.webp"),
    },
    {
        nombre: "Espada de la noche",
        rareza: 3,
        tipo: "espada",
        tipoImg: require("@/assets/images/tipos-armas/weapon_espada.webp"),
        armaImg: require("@/assets/images/armas/swordofnight.webp"),
    },
    {
        nombre: "Pistolas de la noche",
        rareza: 3,
        tipo: "pistolas",
        tipoImg: require("@/assets/images/tipos-armas/weapon_pistolas.webp"),
        armaImg: require("@/assets/images/armas/pistolsofnight.webp"),
    },
    {
        nombre: "Brazales de la noche",
        rareza: 3,
        tipo: "brazales",
        tipoImg: require("@/assets/images/tipos-armas/weapon_brazales.webp"),
        armaImg: require("@/assets/images/armas/gauntletsofnight.webp"),
    },
    {
        nombre: "Rectificador de la noche",
        rareza: 3,
        tipo: "rectificador",
        tipoImg: require("@/assets/images/tipos-armas/weapon_rectificador.webp"),
        armaImg: require("@/assets/images/armas/rectifierofnight.webp"),
    },
    {
        nombre: "Originite: Tipo I",
        rareza: 3,
        tipo: "mandoble",
        tipoImg: require("@/assets/images/tipos-armas/weapon_mandoble.webp"),
        armaImg: require("@/assets/images/armas/originitetype1.webp"),
    },
    {
        nombre: "Originite: Tipo II",
        rareza: 3,
        tipo: "espada",
        tipoImg: require("@/assets/images/tipos-armas/weapon_espada.webp"),
        armaImg: require("@/assets/images/armas/originitetype2.webp"),
    },
    {
        nombre: "Originite: Tipo III",
        rareza: 3,
        tipo: "pistolas",
        tipoImg: require("@/assets/images/tipos-armas/weapon_pistolas.webp"),
        armaImg: require("@/assets/images/armas/originitetype3.webp"),
    },
    {
        nombre: "Originite: Tipo IV",
        rareza: 3,
        tipo: "brazales",
        tipoImg: require("@/assets/images/tipos-armas/weapon_brazales.webp"),
        armaImg: require("@/assets/images/armas/originitetype4.webp"),
    },
    {
        nombre: "Originite: Tipo V",
        rareza: 3,
        tipo: "rectificador",
        tipoImg: require("@/assets/images/tipos-armas/weapon_rectificador.webp"),
        armaImg: require("@/assets/images/armas/originitetype5.webp"),
    },
    {
        nombre: "Mandoble del viajero",
        rareza: 3,
        tipo: "mandoble",
        tipoImg: require("@/assets/images/tipos-armas/weapon_mandoble.webp"),
        armaImg: require("@/assets/images/armas/broadbladeofvoyager.webp"),
    },
    {
        nombre: "Espada del viajero",
        rareza: 3,
        tipo: "espada",
        tipoImg: require("@/assets/images/tipos-armas/weapon_espada.webp"),
        armaImg: require("@/assets/images/armas/swordofvoyager.webp"),
    },
    {
        nombre: "Rectificador del viajero",
        rareza: 3,
        tipo: "rectificador",
        tipoImg: require("@/assets/images/tipos-armas/weapon_rectificador.webp"),
        armaImg: require("@/assets/images/armas/rectifierofvoyager.webp"),
    },
    {
        nombre: "Pistolas del viajero",
        rareza: 3,
        tipo: "pistolas",
        tipoImg: require("@/assets/images/tipos-armas/weapon_pistolas.webp"),
        armaImg: require("@/assets/images/armas/pistolsofvoyager.webp"),
    },
    {
        nombre: "Brazales del viajero",
        rareza: 3,
        tipo: "brazales",
        tipoImg: require("@/assets/images/tipos-armas/weapon_brazales.webp"),
        armaImg: require("@/assets/images/armas/gauntletsofvoyager.webp"),
    },
    {
        nombre: "Mandoble de guardián",
        rareza: 3,
        tipo: "mandoble",
        tipoImg: require("@/assets/images/tipos-armas/weapon_mandoble.webp"),
        armaImg: require("@/assets/images/armas/guardianbroadblade.webp"),
    },
    {
        nombre: "Espada de guardián",
        rareza: 3,
        tipo: "espada",
        tipoImg: require("@/assets/images/tipos-armas/weapon_espada.webp"),
        armaImg: require("@/assets/images/armas/guardiansword.webp"),
    },
    {
        nombre: "Rectificador de guardián",
        rareza: 3,
        tipo: "rectificador",
        tipoImg: require("@/assets/images/tipos-armas/weapon_rectificador.webp"),
        armaImg: require("@/assets/images/armas/guardianrectifier.webp"),
    },
    {
        nombre: "Pistolas de guardián",
        rareza: 3,
        tipo: "pistolas",
        tipoImg: require("@/assets/images/tipos-armas/weapon_pistolas.webp"),
        armaImg: require("@/assets/images/armas/guardianpistols.webp"),
    },
    {
        nombre: "Brazales de guardián",
        rareza: 3,
        tipo: "brazales",
        tipoImg: require("@/assets/images/tipos-armas/weapon_brazales.webp"),
        armaImg: require("@/assets/images/armas/guardiangauntlets.webp"),
    },
    {
        nombre: "Melodía cautivadora",
        rareza: 3,
        tipo: "mandoble",
        tipoImg: require("@/assets/images/tipos-armas/weapon_mandoble.webp"),
        armaImg: require("@/assets/images/armas/beguilingmelody.webp"),
    },
    {
        nombre: "Mandoble de principiante",
        rareza: 2,
        tipo: "mandoble",
        tipoImg: require("@/assets/images/tipos-armas/weapon_mandoble.webp"),
        armaImg: require("@/assets/images/armas/tyrobroadblade.webp"),
    },
    {
        nombre: "Espada de principiante",
        rareza: 2,
        tipo: "espada",
        tipoImg: require("@/assets/images/tipos-armas/weapon_espada.webp"),
        armaImg: require("@/assets/images/armas/tyrosword.webp"),
    },
    {
        nombre: "Rectificador de principiante",
        rareza: 2,
        tipo: "rectificador",
        tipoImg: require("@/assets/images/tipos-armas/weapon_rectificador.webp"),
        armaImg: require("@/assets/images/armas/tyrorectifier.webp"),
    },
    {
        nombre: "Pistolas de principiante",
        rareza: 2,
        tipo: "pistolas",
        tipoImg: require("@/assets/images/tipos-armas/weapon_pistolas.webp"),
        armaImg: require("@/assets/images/armas/tyropistols.webp"),
    },
    {
        nombre: "Brazales de principiante",
        rareza: 2,
        tipo: "brazales",
        tipoImg: require("@/assets/images/tipos-armas/weapon_brazales.webp"),
        armaImg: require("@/assets/images/armas/tyrogauntlets.webp"),
    },
    {
        nombre: "Mandoble de entrenamiento",
        rareza: 1,
        tipo: "mandoble",
        tipoImg: require("@/assets/images/tipos-armas/weapon_mandoble.webp"),
        armaImg: require("@/assets/images/armas/trainingbroadblade.webp"),
    },
    {
        nombre: "Espada de entrenamiento",
        rareza: 1,
        tipo: "espada",
        tipoImg: require("@/assets/images/tipos-armas/weapon_espada.webp"),
        armaImg: require("@/assets/images/armas/trainingsword.webp"),
    },
    {
        nombre: "Rectificador de entrenamiento",
        rareza: 1,
        tipo: "rectificador",
        tipoImg: require("@/assets/images/tipos-armas/weapon_rectificador.webp"),
        armaImg: require("@/assets/images/armas/trainingrectifier.webp"),
    },
    {
        nombre: "Pistolas de entrenamiento",
        rareza: 1,
        tipo: "pistolas",
        tipoImg: require("@/assets/images/tipos-armas/weapon_pistolas.webp"),
        armaImg: require("@/assets/images/armas/trainingpistols.webp"),
    },
    {
        nombre: "Brazales de entrenamiento",
        rareza: 1,
        tipo: "brazales",
        tipoImg: require("@/assets/images/tipos-armas/weapon_brazales.webp"),
        armaImg: require("@/assets/images/armas/traininggauntlets.webp"),
    },
]