export default [
    {
        nombre: "Esmeralda del génesis",
        rareza: 5,
        tipo: "espada",
        tipoImg: require("@/assets/images/tipos-armas/weapon_espada.webp"),
        armaImg: require("@/assets/images/armas/esmeraldadelgenesis.webp"),
    },
    {
        nombre: "Ondas cósmicas",
        rareza: 5,
        tipo: "rectificador",
        tipoImg: require("@/assets/images/tipos-armas/weapon_rectificador.webp"),
        armaImg: require("@/assets/images/armas/ondascosmicas.webp"),
    },
    {
        nombre: "Niebla estática",
        rareza: 5,
        tipo: "pistola",
        tipoImg: require("@/assets/images/tipos-armas/weapon_pistola.webp"),
        armaImg: require("@/assets/images/armas/nieblaestatica.webp"),
    },
    {
        nombre: "Navaja brillante",
        rareza: 5,
        tipo: "mandoble",
        tipoImg: require("@/assets/images/tipos-armas/weapon_mandoble.webp"),
        armaImg: require("@/assets/images/armas/navajabrillante.webp"),
    },
    {
        nombre: "Oleadas del abismo",
        rareza: 5,
        tipo: "brazales",
        tipoImg: require("@/assets/images/tipos-armas/weapon_brazales.webp"),
        armaImg: require("@/assets/images/armas/oleadasdelabismo.webp"),
    },
    {
        nombre: "Cumbre verde",
        rareza: 5,
        tipo: "mandoble",
        tipoImg: require("@/assets/images/tipos-armas/weapon_mandoble.webp"),
        armaImg: require("@/assets/images/armas/verdantsummit.webp"),
    },
    {
        nombre: "Maestro de cuerdas",
        rareza: 5,
        tipo: "rectificador",
        tipoImg: require("@/assets/images/tipos-armas/weapon_rectificador.webp"),
        armaImg: require("@/assets/images/armas/stringmaster.webp"),
    },
    {
        nombre: "Eras de cosecha",
        rareza: 5,
        tipo: "mandoble",
        tipoImg: require("@/assets/images/tipos-armas/weapon_mandoble.webp"),
        armaImg: require("@/assets/images/armas/agesofharvest.webp"),
    },
    {
        nombre: "Brillo abrasador",
        rareza: 5,
        tipo: "espada",
        tipoImg: require("@/assets/images/tipos-armas/weapon_espada.webp"),
        armaImg: require("@/assets/images/armas/blazingbrilliance.webp"),
    },
    {
        nombre: "Espina de la desafiadora",
        rareza: 5,
        tipo: "espada",
        tipoImg: require("@/assets/images/tipos-armas/weapon_espada.webp"),
        armaImg: require("@/assets/images/armas/defiersthorn.webp"),
    },
    {
        nombre: "Brotes escarchados",
        rareza: 5,
        tipo: "rectificador",
        tipoImg: require("@/assets/images/tipos-armas/weapon_rectificador.webp"),
        armaImg: require("@/assets/images/armas/rimedraped.webp"),
    },
    {
        nombre: "Mango de la verdad",
        rareza: 5,
        tipo: "brazales",
        tipoImg: require("@/assets/images/tipos-armas/weapon_brazales.webp"),
        armaImg: require("@/assets/images/armas/verity.webp"),
    },
    {
        nombre: "Sinfonía estelar",
        rareza: 5,
        tipo: "rectificador",
        tipoImg: require("@/assets/images/tipos-armas/weapon_rectificador.webp"),
        armaImg: require("@/assets/images/armas/stellarsymphony.webp"),
    },
    {
        nombre: "Primavera roja",
        rareza: 5,
        tipo: "espada",
        tipoImg: require("@/assets/images/tipos-armas/weapon_espada.webp"),
        armaImg: require("@/assets/images/armas/redspring.webp"),
    },
    {
        nombre: "Tragicomedia",
        rareza: 5,
        tipo: "brazales",
        tipoImg: require("@/assets/images/tipos-armas/weapon_brazales.webp"),
        armaImg: require("@/assets/images/armas/tragicomedy.webp"),
    },
    {
        nombre: "Último baile",
        rareza: 5,
        tipo: "pistola",
        tipoImg: require("@/assets/images/tipos-armas/weapon_pistola.webp"),
        armaImg: require("@/assets/images/armas/lastdance.webp"),
    },
    {
        nombre: "Valor inquebrantable",
        rareza: 5,
        tipo: "espada",
        tipoImg: require("@/assets/images/tipos-armas/weapon_espada.webp"),
        armaImg: require("@/assets/images/armas/unflickering.webp"),
    },
    {
        nombre: "Himno luminoso",
        rareza: 5,
        tipo: "rectificador",
        tipoImg: require("@/assets/images/tipos-armas/weapon_rectificador.webp"),
        armaImg: require("@/assets/images/armas/luminoushymn.webp"),
    },
    {
        nombre: "Susurros de sirenas",
        rareza: 5,
        tipo: "rectificador",
        tipoImg: require("@/assets/images/tipos-armas/weapon_rectificador.webp"),
        armaImg: require("@/assets/images/armas/whispersofsirens.webp"),
    },
    {
        nombre: "Pacto de sangre",
        rareza: 5,
        tipo: "espada",
        tipoImg: require("@/assets/images/tipos-armas/weapon_espada.webp"),
        armaImg: require("@/assets/images/armas/bloodpacts.webp"),
    },
    {
        nombre: "Veredicto del destello",
        rareza: 5,
        tipo: "brazales",
        tipoImg: require("@/assets/images/tipos-armas/weapon_brazales.webp"),
        armaImg: require("@/assets/images/armas/blazingjustice.webp"),
    },
    {
        nombre: "Aria del bosque",
        rareza: 5,
        tipo: "pistola",
        tipoImg: require("@/assets/images/tipos-armas/weapon_pistola.webp"),
        armaImg: require("@/assets/images/armas/woodlandaria.webp"),
    },
    {
        nombre: "Disonancia",
        rareza: 4,
        tipo: "mandoble",
        tipoImg: require("@/assets/images/tipos-armas/weapon_mandoble.webp"),
        armaImg: require("@/assets/images/armas/discord.webp"),
    },
    {
        nombre: "Obertura",
        rareza: 4,
        tipo: "espada",
        tipoImg: require("@/assets/images/tipos-armas/weapon_espada.webp"),
        armaImg: require("@/assets/images/armas/overture.webp"),
    },
]